# Gradle

# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main

pool: 
  vmImage: ubuntu-latest

steps:
  - checkout: self
    fetchDepth: 0
  - task: SonarCloudPrepare@1
    displayName: "Preparing sonar cloud"
    inputs:
      SonarCloud: 'sonar-connection'
      organization: 'deimercegarra'
      scannerMode: 'Other'
  - task: Gradle@3
    displayName: 'Building gradle project'
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'clean build sonar'
      jdkVersionOption: '1.17'

  - task: SonarCloudPublish@1
    displayName: 'Publishing sonarResults'
    inputs:
      pollingTimeoutSec: '300'

  - task: Docker@2
    inputs:
      containerRegistry: 'docker-hub-connection'
      repository: 'deimercegarra/boulevard_micro_devops'
      tags: 'latest'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'


